### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by mokanfar** [magesec/patchrepo#3]
New M1 SUPEE came out been 1 week already, usually this gets addressed in couple days by your team

**Comment by gnuzealot** [comment]
It is, we are working on getting the new patch integrated today

**Comment by mrhambley** [comment]
Great news :) Will the new update include SUPEE 11219 (version 2)?

**Comment by gnuzealot** [comment]
Yes, new patches have just been applied and uploaded.
